const nome = prompt('Digite seu Nome completo: ')
        document.body.innerHTML += `O seu nome é ${nome} <br/>`;
        document.body.innerHTML += `Seu nome tem ${nome.length} letras <br />`;
        document.body.innerHTML += `A segunda letra do seu nome é: <strong>${nome.charAt(1)}</strong><br />`;
        document.body.innerHTML += `Qual o primeiro índice da letra "d" no seu nome? <strong>${nome.indexOf('d')}</strong><br />`;
        document.body.innerHTML += `Qual o último índice da letra "e" no seu nome? <strong>${nome.lastIndexOf('e')}</strong><br />`;
        document.body.innerHTML += `As últimas 3 letras do seu nome são: <strong>${nome.slice(-3)}</strong><br />`;
        document.body.innerHTML += `As palavras do seu nome são: <strong>${nome.split(' ')}</strong><br />`;
        document.body.innerHTML += `Seu nome com letras maiúsculas: <strong>${nome.toUpperCase()}</strong><br />`;
        document.body.innerHTML += `Seu nome com letras minúsculas:<strong> ${nome.toLowerCase()}</strong><br />`;